# Generated by Django 4.1.7 on 2023-03-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asosiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(upload_to='asosiy')),
                ('matn_uz', models.CharField(max_length=500)),
                ('matn_rus', models.CharField(max_length=500)),
                ('matn_ingliz', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BizningUylar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_uz', models.CharField(max_length=150)),
                ('nom_rus', models.CharField(max_length=150)),
                ('nom_ingliz', models.CharField(max_length=150)),
                ('kenglik', models.PositiveSmallIntegerField()),
                ('kirish', models.PositiveSmallIntegerField()),
                ('mehmonxona', models.PositiveSmallIntegerField()),
                ('oshxona', models.PositiveSmallIntegerField()),
                ('shahar', models.CharField(max_length=150)),
                ('sotuvda_bor', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fasad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(upload_to='fasad')),
            ],
        ),
        migrations.CreateModel(
            name='KaryuselRasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(upload_to='karyusel')),
            ],
        ),
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_uz', models.CharField(max_length=300)),
                ('nom_rus', models.CharField(max_length=300)),
                ('nom_ingliz', models.CharField(max_length=300)),
                ('loyiha_haqida_uz', models.CharField(max_length=300)),
                ('loyiha_haqida_rus', models.CharField(max_length=300)),
                ('loyiha_haqida_ingliz', models.CharField(max_length=300)),
                ('loyiha_haqida_rasm', models.FileField(upload_to='', verbose_name='loyiha_haqida')),
                ('bizning_ishlar_uz', models.CharField(max_length=300)),
                ('bizning_ishlar_rus', models.CharField(max_length=300)),
                ('bizning_ishlar_ingliz', models.CharField(max_length=300)),
                ('bizning_ishlar_rasm', models.FileField(upload_to='bizning_ishlar')),
                ('infratuzilma_uz', models.CharField(max_length=300)),
                ('infratuzilma_rus', models.CharField(max_length=300)),
                ('infratuzilma_ingliz', models.CharField(max_length=300)),
                ('infratuzilma_rasm', models.FileField(upload_to='infratuzilma')),
                ('afzalliklar_uz', models.CharField(max_length=300)),
                ('afzalliklar_rus', models.CharField(max_length=300)),
                ('afzalliklar_ingliz', models.CharField(max_length=300)),
                ('afzalliklar_rasm', models.FileField(upload_to='afzalliklar')),
            ],
        ),
    ]
